# Generated by Django 2.0.7 on 2018-07-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=200)),
                ('location_hint', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt.Clue')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
