# Generated by Django 2.0.7 on 2018-07-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClueState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField()),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt.Clue')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt.Team')),
            ],
        ),
    ]
