# Generated by Django 2.0.7 on 2018-08-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_cluestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.CharField(default='default_email', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default='password', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
